#! /usr/bin/env sh
host="${1}"
cert_file="${2}"
key_file="${3}"
chain_file="${4}"

echo "Host: ${host}"
echo "Certificate File: ${cert_file}"
echo "Key File: ${key_file}"
echo "Chain File: ${chain_file}"
