#! /usr/bin/env sh

event="${1}"
host="${2}"
cert_file="${3}"
key_file="${4}"
chain_file="${5}"

if [ "${event}" != "pre" ]
then
    exit 0
fi

echo "Host: ${host}"
echo "Certificate File: ${cert_file}"
echo "Key File: ${key_file}"
echo "Chain File: ${chain_file}"
