#! /usr/bin/env sh

event="${1}"
host="${2}"
root_dir="${3}"
conf_conf="${4}"
conf_include="${5}"
site_conf="${6}"
site_include="${7}"

if [ "${event}" != "pre" ]
then
    exit 0
fi

echo "Host: ${host}"
echo "Root Document: ${root_dir}"
echo "Http Configuration Source: ${conf_conf}"
echo "Site Configuration Source: ${conf_include}"
echo "Http Configuration Destination: ${site_conf}"
echo "Site Configuration Destination: ${site_include}"
